path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
  - BH (>= 1.75.0-0)
  - RcppEigen (>= 0.3.3.9.3)
  - rstan (>= 2.26.0)
pkg_ignore: ~
document: yes
normalize: yes
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
